### PR TITLE
new plugin soar for sql.

### PR DESCRIPTION
**Pull request by liipx**
https://github.com/liipx/SublimeLinter-soar

### CODE REVIEW

**Comment by liipx** [comment]
SublimLinter-soar is a sql linter based on [SOAR](https://github.com/XiaoMi/soar)，it will give heuristic suggestions and index advices for queries.

that screenshot shows how it works:
p

**Comment by kaste** [comment]
Hi! That's an interesting linter, hopefully you get it translated to english.

Two things:

```
cmd = persist.settings.get('linters').get('soar').get("soar_path") + " -report-type lint -query"
```

This doesn't work bc for normal users the settings aren't ready on import/parse time. It's actually not necessary as well bc all SublimeLinter linters have a common setting `executable` http://www.sublimelinter.com/en/stable/linter_settings.html#executable which does the exact same thing and you don't have to do anything to support it.

So the cmd basically could look like 

```
cmd = "soar -report-type lint -query $temp_file"
```

`$temp_file` at the end to make it clear that this linter works with temporary files.

2. Setting `col=0` is a bit unusual bc it means you always mark the word at beginning of the line. Note that this doesn't mark anything useful if the user indents his sql expression.

**Comment by liipx** [comment]
tks so much for response.
I'll fix them recently.

**Comment by kaste** [comment]
Some tips and tricks here. Note that only the `cmd` thing is a blocker for merge. The `col` stuff is optional bc you can fix and enhance the linter whenever you want.

If you leave `col = None` which is the default, you can tell SublimeLinter to search for a word on the offending line using `near`. E.g. if you set `near` to `SELECT` it will mark the first word 'SELECT' on that line.

Furthermore, if you extract 'COL.001' or something like that and put it as `error` *or* `warning` SublimeLinter will set the 'error_type' to error (or warning) and will use the string as the rule name. E.g. it will set 'COL.001' or 'CLA.001' as the rule. This usually help people in finding the appropriate documentation. It also enables fancy styling bc every rule and every error_type can be styled (or hidden) in various ways.

**Comment by braver** [comment]
Closed due to age and inactivity.

**Pull request closed without merging**
