### PR TITLE
Add SublimeLinter-contrib-checkmake to contrib.json

### PR DESCRIPTION
**Pull request by mcw0933**
https://github.com/mcw0933/SublimeLinter-contrib-checkmake

### CODE REVIEW

**Comment by braver** [comment]
I wonder if it makes sense or publish a plugin for this linter. The linter never left experimental status and seems to have been abandoned a few years ago.

**Comment by kaste** [comment]
The plugin code LGTM and could 🚢 . Can't say anything on the linter of course.

**Comment by mcw0933** [comment]
> I wonder if it makes sense or publish a plugin for this linter. The linter never left experimental status and seems to have been abandoned a few years ago.

Agree, but there doesn't seem to be any newer / more active tool for linting Makefiles.  I have been using this one and it's better than nothing.

**Comment by braver** [comment]
Ok! 👌

**Pull request merged**
