### PR TITLE
Added credo

### PR DESCRIPTION
**Pull request by mintcore**

### CODE REVIEW

**Comment by lATAl** [comment]
Any update for this?

**Comment by mintcore** [comment]
@lATAl Not sure whether the repo author hasn't had the time to review or something else. Haven't heard anything from anyone :(

**Comment by lATAl** [comment]
@groteworld Bro, if possible can you take a look at this?

**Comment by groteworld** [comment]
Has this package gone under review? I don't think I've seen a sublimelinter issue? More info about our review process here http://www.sublimelinter.com/en/latest/creating_a_linter.html#preparing-for-publication

**Comment by braver** [comment]
@mintcore if you can resolve the conflict for me I'll merge it.

**Comment by mintcore** [comment]
It seems like another credo snook in between and merged between this pr was opened and now (b3c18864eada2311b153bc8b5fb80d88faade9cf). So I guess this this should just be closed? Or should I take the opportunity to fix the incorrect spelling of elixir?

**Comment by braver** [comment]
Indeed let’s close this. If you want to fix something else you’re very welcome to open a new pr for it.

**Pull request closed without merging**
