### PR TITLE
Adds SublimeLinter-roslint

### PR DESCRIPTION
**Pull request by Sotilrac**
Adds roslint support for C++ linting in ROS.

### CODE REVIEW

**Comment by braver** [comment]
Hi! Please create a (semver compatible, so 1.0.0 or 0.1.0 or something) release on your repo.

**Comment by kaste** [comment]
Hi! Does this linter operate on stdin or temp files? Right now it will effectively use stdin and $temp_file will be replaced with the empty string.

**Comment by Sotilrac** [comment]
@braver  Release created: [0.1.0](https://github.com/Sotilrac/SublimeLinter-roslint/releases/tag/0.1.0)
Also @kaste , I fixed the superfluous $temp_file. Thanks for pointing it out.

**Comment by braver** [comment]
Awesome

**Pull request merged**
