### PR TITLE
Added SublimeLinter-contrib-checkstyle

### PR DESCRIPTION
**Pull request by LDAP**

### CODE REVIEW

**Comment by kaste** [comment]
I think this looks okayish but it has a lot of code which we usually don't see for linter adapters to SublimeLinter.  I appreciate the extra work you did here.  

- It really looks like you run `checkstyle_version` with its side-effect of going over the internet on every `cmd` call.  This totally looks like a waste.  I don't think you should do this and it shouldn't be necessary to do this for example on every save (typically for this linter).  Also: the framework might want to call `cmd()` on other occasions, just to see if this linter is runnable and which executable it wants.  (Typically, `cmd` is just declarative but even if you define it as a method/callable it should be in some sense "pure".)

- It looks like `self.checkstyle_jar` can be unbound (t.i. `None`) at the time you do `command = ['java', '-jar', '{}'.format(self.checkstyle_jar)]`

- `self.debug` or `settings.get('debug')` might be redundant.  Why not use the global SublimeLinter `debug` setting here?  You *can* use your own panel but isn't the normal logging SublimeLinter provides for free enough?  (The standard logging naturally listens for the debug setting, t.i. it does not log `info` messages but always logs `warning` to the console, and prints `error` and `exception` to a panel.)

- `self.name` should be just `checkstyle`.  You could omit it altogether if you name the class just `Checkstyle`.  (You use this name in your code for other purposes but that's not the meaning of `name`.  `name` is a distinct, *user visible* name used in the store/database and in the views. "SublimeLinter-" is not a good prefix here since it is not a shared namespace with other frameworks.)

**Comment by LDAP** [comment]
Thank you for your review. I am new to python and the SL codebase maybe you can help me out with some things:
- I knew that running `checkstyle_version` on every save is a bad idea. I could not figure out how to persist data. SL seems to recreate the object on every call of `cmd`
- What do you mean by unbound in your second point?
- I did not know about the debugging options of SL. Is there any developer focused documentation i missed?

(I am busy the next few weaks it may take a while until I release a new version)

**Comment by kaste** [comment]
That's very good python you wrote here.

1. For this purpose a global is probably the correct answer because you basically just resolve what "latest" means.  Maybe requesting this once per Sublime start is enough, or once a day.  Basically 

```
CURRENT_LATEST_VERSION = None
```

on the module level.  In python, you then usually do:

```
def cmd(...).
	global CURRENT_LATEST_VERSION
	...
```

at the top of a function/method to make the global available.  To persist the value over hot-reloading the code, you can use the following pattern:

```
try:
	CURRENT_LATEST_VERSION
except NameError:
	CURRENT_LATEST_VERSION = None
```

I think this is the correct, still simple level of persistence for the problem. 

2. "Unbound" is *technically* not the correct term I used here since you init to `None`, but at the time you *use* `self.checkstyle_jar` for the actual `command` it is not guaranteed to be not `None`.  At least that's how I read the code.  Maybe you can write the code and ensure it is never None, otherwise you maybe need to throw here to abort. 
What to throw here?  If it's more like a fluke, network error, disk error, you throw a `TransientError`, if there is something a user *must* configure or install, somehow change, you throw a `PermanentError`.

```
from SublimeLinter.lint.linter import PermanentError, TransientError  

def cmd(...):
	logger.warning("...")  # or logger.error("X happenend. Please install Y.")
	self.notify_failure()
	raise TransientError()
```

3. There is currently no other documentation.

```
import logging
logger = logging.getLogger("SublimeLinter.plugin.checkstyle")  # the `name` of the linter!
```

The debug mode can be set in the SublimeLinter settings.  Via Command Palette `ctrl+shift+p` then `Preferences: SublimeLinter Settings`.

**Comment by LDAP** [comment]
Thank you a lot for your help.

Have a look at my `dev` branch. Ive got everything working except the logging. Setting debug to true in the SL settings outputs a lot of messages from SL itself but my own logger.info calls seemd to be ignored. logger.waring/error are working fine. You can try it yourself by replacing print_debug(msg) with def logger.info(msg). Did I missed something again?

**Comment by kaste** [comment]
Hm, you use 

```
logger = logging.getLogger(__name__)
```
 
but it should be 

```
logger = logging.getLogger("SublimeLinter.plugin.checkstyle")
```

This is a namespace, and SublimeLinter only registers, receives and prints the "SublimeLinter" namespace.

**Comment by LDAP** [comment]
> 
> 
> Hm, you use
> 
> ```
> logger = logging.getLogger(__name__)
> ```
> 
> but it should be
> 
> ```
> logger = logging.getLogger("SublimeLinter.plugin.checkstyle")
> ```
> 
> This is a namespace, and SublimeLinter only registers, receives and prints the "SublimeLinter" namespace.

That fixed it. Thank you.

Please review again against my master

**Comment by kaste** [comment]
LGTM.  

- It is better to inline all constants because of how hot-reloading works in Sublime.  `constants.py` is small enough and you avoid the problem having `constants.py` and `linter.py` not in sync at some point.  

- `fetch_latest_cs_version() -> str` actually does never return a `str` although it probably should.  You also don't need to unconditionally call it at the beginning of `cmd` but probably in `cs_version(self) -> str` because if the user specifies a concrete `version` you never need to resolve "latest".

**Comment by LDAP** [comment]
Update pushed

**Comment by kaste** [comment]
That works really great, and unbelievable convenient, user-friendly as it just downloads what it needs.  👍  You literally just install/git clone the plugin wait 10 seconds and have a result.

**Comment by LDAP** [comment]
:)

**Pull request merged**
