### PR TITLE
Add SublimeLinter-contrib-healthier

### PR DESCRIPTION
**Pull request by KidkArolis**
Add https://github.com/KidkArolis/SublimeLinter-contrib-healthier

Which is an integration for https://github.com/KidkArolis/healthier

Question.. will this make the package show up in Sublime's Package Manager? Or do I need an additional step for that to work?

### CODE REVIEW

**Comment by kaste** [comment]
Hi @KidkArolis!

Where did you get this code from? Almost everything here is deprecrated 😁 

- Please enable debug mode for SublimeLinter which will hopefully show all deprecation warnings. 
- I don't think `self.syntax` is a thing. Have you tested your code that it even runs?

**Comment by kaste** [comment]
EDIT: Okay, you define `syntax` on the class so `self.syntax` will probably just refer to that.

**Comment by KidkArolis** [comment]
Hi, any help would be appreciated. I'm happy to copy a better template if you can suggest something similar.

I've copied it from here: https://github.com/Flet/SublimeLinter-contrib-standard since `healthier` is using `standard-engine` under the hood.

And it does work! I'm using it right now.

One more question, how do I simultanously edit the plugin code and load the dev version into Sublime? I couldn't find any docs for that. Right now install from git to test, but it's packaged up and I can't edit..

**Comment by kaste** [comment]
For dev, you usually `git clone` into Sublime's package folder. (The folder you get on `Preferences > Browse Packages`.)

Yes it works but it will probably not work in a couple of weeks 😁

**Comment by KidkArolis** [comment]
@kaste thanks for the tip about the debug mode

I've updated the code, could you have another look?

If it's easier, here's the code:

```py
"""This module exports the Healthier plugin class."""

import re
from SublimeLinter.lint import NodeLinter

class Healthier(NodeLinter):
    """Provides an interface to healthier."""

    cmd = 'healthier --stdin --verbose'
    regex = r'^\s.+:(?P<line>\d+):(?P<col>\d+):(?P<message>.+)'
    defaults = {
        'selector': 'source.js - meta.attribute-with-value',
        'disable_if_not_dependency': True
    }

    def on_stderr(self, stderr):
        if ('healthier: Friendly linter' in stderr):
            return
        else:
            logger.error(stderr)

    def run(self, cmd, code):
        return super().run(cmd, code)
```

**Comment by kaste** [comment]
That looks great. (You don't need to implement run, it only calls super right now.)

@braver for merge

**Comment by KidkArolis** [comment]
@braver tag v1.0.0 and moved into alphabetical order.

**Comment by braver** [comment]
Whoop! 🎉

**Pull request merged**
