### PR TITLE
Add SublimeLinter-contrib-brew

### PR DESCRIPTION
**Pull request by idleberg**

### CODE REVIEW

**Comment by kaste** [comment]
Hi 👋 !

`syntax` has been deprecated in favor of `selector` http://www.sublimelinter.com/en/stable/linter_settings.html#selector

Something like this 

```
	defaults = {
		'selector': 'source.ruby'
	}
```

**Comment by idleberg** [comment]
Thanks. Fixed in v0.1.1

**Comment by braver** [comment]
Looks good to me, @kaste agree?

@idleberg Our [standard README](https://github.com/SublimeLinter/SublimeLinter-template/blob/master/README.md) has been updated to be less verbose, more to the point and more friendly. You may want to have a look, see if it makes sense for your plugin too.

**Comment by kaste** [comment]
👍 🚢 🇮🇹 

BTW `.sublimelinterrc` is not a thing anymore. You can delete the file.

**Pull request merged**
