### PR TITLE
Add SublimeLinter-contrib-glslc

### PR DESCRIPTION
**Pull request by MarioHenze**

### CODE REVIEW

**Comment by kaste** [comment]
Hi!  

Looks like `glslc` actually works on files written to disk (t.i. after save).  Currently, you wrote the adapter plugin for *stdin* input.  To enable *file-on-disk* "mode" you have to set the class variable `tempfile_suffix = '-'`, and instead of `${file}`, use `${file_on_disk}` as the marker in `cmd`. 

You also have to make a first release using semantic versioning.

Not that important, but the README file stills begins with some standard text from the template. 

Otherwise looks good.

**Comment by MarioHenze** [comment]
Hi

Curiously the linter worked already before changing these options. But I've made them nonetheless.

**Comment by kaste** [comment]
Yeah it works but only for small files.  As we push the file contents via stdin it breaks as soon as the file buffer is full and then blocks because the linter will never read from that buffer.

**Comment by kaste** [comment]
:ship:'ed

**Pull request merged**
