### PR TITLE
Added SublimeLinter-contrib-radon

### PR DESCRIPTION
**Pull request by christopherpickering**
https://github.com/christopherpickering/SublimeLinter-contrib-radon

Show radon complexity on python functions/classes/modules.

### CODE REVIEW

**Comment by kaste** [comment]
Ah cool.

I think the `col` is off by one.  Probably set

```
    line_col_base = (1, 0)
```

In `split_mmatch` you use the basically deprecated form of unpacking-the-tuple and return a-massive-tuple.  

You can simplify our life by doing for example

```
    rv = super().split_match(match)  # always truthy
	rv['message'] = message_code[match.group('code')]  # as an example
	return rv
```

I would like to have the key `code` relatively stable, maybe just ABCD...  as we can then apply different styles to these classifications.  Say, make A green and F violet.  Or B invisible and EF with an icon.  (If the code is more dynamic, like `B 12`, this becomes very hard as a user had to define all possible values.) We could also more easily filter some error types, via `filter_errors`, as for example a cc of `B` is actually just fine.  

I actually think having the function, class name in the message also helps in orientation when looking at error panel.  Not sure though.

Why not use 

```
    cmd = 'radon cc ${temp_file} -s ...'
    tempfile_suffix = 'py'
```

for live updates while typing.  Then a user can still downgrade via `lint_mode`. 

Ah, well, too many suggestions already.  `line_col_base` is important, and a sane/stable `code` because the styles rely on it.

**Comment by christopherpickering** [comment]
Great, thanks for the feedback, I appreciate it! I'll put out an update with those recommendations.

**Comment by kaste** [comment]
For example, 

image

with that I have already a lot of information in the error panel.

**Comment by christopherpickering** [comment]
@kaste , thanks for the feedback, I think I've updated everything you recommended. I realized I was following the docs for v4 and completely lost as most things do not seem to be in those docs yet lol. I have "stable" now.

image


I don't understand your comments on color & icon, I haven't seen a linter use icons or colors in the message? Can you send me an example of one?

**Comment by kaste** [comment]
About color & icon.  With these simple "codes" *a user* can style them.  E.g.

```
        "radon": {
            "styles": [
                {
                    "codes": ["A", "B", "C"],
                    "mark_style": "none",
                    // "icon": "none"
                }
            ]
        },
```

With `mark_style: none` you can disable the underlining, and keep the icon.  Or set both to `none` then the warnings will only appear in the error panel.  etc.

You need to make a first release now, like 1.0.0.

I saw you struggled with the capture groups `warning` vs. `error`, as these do multiple things.  Typically in newer code: don't use them and just set `output["error_type"] = "warning"  # or "error" or for example "info"`  The error type can also used in the styles so instead of `"codes": ["A", "B", "C"],` a user could set `"types": ["info"]` to target multiple ranks.

Ping me again when you made a tagged release.

**Comment by christopherpickering** [comment]
ok, cool, thanks!
Here's the [release](https://github.com/christopherpickering/SublimeLinter-contrib-radon/releases/tag/1.0.0)

**Comment by kaste** [comment]
Let's ship it!

**Pull request merged**
