### PR TITLE
Add WebHare Linter package

### PR DESCRIPTION
**Pull request by krisbreuker**

### CODE REVIEW

**Comment by braver** [comment]
Hi, thanks for the PR. Your linter is a bit outdated and declares attributes that aren’t supported anymore (e.g. the inline_ stuff) or deprecated (e.g. syntax). Please check the documentation for SublimeLinter 4: http://www.sublimelinter.com/en/stable/linter_attributes.html

**Comment by krisbreuker** [comment]
Thanks for your feedback. Can you please check again, or should I close and reopen the PR?

**Comment by braver** [comment]
Looks good. Usually we put some general info in the readme, with a link to info about the actual linter executable. You can use the boilerplate from here: https://github.com/SublimeLinter/SublimeLinter-template/blob/master/README.md

**Comment by krisbreuker** [comment]
I have updated the readme, but as we're still in the process of getting our documentation in order, it just has a placeholder for the actual setup instructions.

**Comment by braver** [comment]
Excellent, thanks!

**Pull request merged**
