### PR TITLE
Added darglint plugin

### PR DESCRIPTION
**Pull request by raddessi**
Yet another docstring linter, but I like it :) Props to the actual developers

### CODE REVIEW

**Comment by braver** [comment]
Cool, looks good! Please make a 1.0.0 release, then we can merge.

**Comment by kaste** [comment]
Two notes:

Both 

```
        'default_type': WARNING,
        'tempfile_suffix': 'py',
```

don't go into `defaults` (which holds default settings a user can configure) but on the class as members.

This is super important if you actually want to use the tempfile feature. Right now, we would send the buffer content via stdin to the linter. But if the linter doesn't allow stdin and thus will not read from it, it will result in BrokenPipe exceptions for any larger file.

However, if you really use tempfiles then the `cmd` should not be invoked with `${file}` probably which holds the actual, real filename of the buffer but with `${temp_file}` instead. The latter context variable will hold the filename of the newly, created temporary file.

**Comment by kaste** [comment]
You could also quickly send a PR to darglint to enable stdin support. Seems easy enough https://github.com/terrencepreilly/darglint/blob/b20c0f464c841c03e8c2870d4fbe8b1387ce2881/darglint/function_description.py#L19:5 If filename is '-' read stdin.

**Comment by raddessi** [comment]
Ah totally, I like the idea of actually patching for reading from stdin much better, I'll get with him for that! Thanks for the review, I must have misread the docs around the `default_type` and `tempfile_suffix`, I'll move `default_type` and remove the tempfile related stuff once we get darglint to read from stdin.

Have a great week!

**Comment by braver** [comment]
Closed due to age and inactivity.

**Pull request closed without merging**
