### PR TITLE
adding cspell based spell check linter

### PR DESCRIPTION
**Pull request by hsghori**
Adding a linter to spell check camel case, snake case, etc words in source code files.

### CODE REVIEW

**Comment by braver** [comment]
Hi! Looks really useful 👍🏻 Todo:

- it should be called SublimeLinter-contrib-cspell, plug-ins are named after the utility it runs.
- make a 1.0.0 release

**Comment by hsghori** [comment]
how do I make it a 1.0.0 release?

**Comment by hsghori** [comment]
Thanks! Done.

**Comment by kaste** [comment]
Hi @hsghori! Interesting linter you've found here.

I guess the linter only lints the real files on disk not the buffer content in Sublime. 

If that's the case, you must set `tempfile_suffix = '-'` (yes this is ugly, we're working on it.), otherwise the linter will crash on large files. Instead of `$file` use `$file_on_disk` for future compatibility. 

If the linter uses STDIN for reading everything is fine. 👌 

🎄

**Comment by kaste** [comment]
Ah, `re.compile` is strictly not necessary because SublimeLinter will do this for you *automatically*. 🥃

**Comment by braver** [comment]
@hsghori can you also update the PR for the new URL? Also, had a look at @kaste's remarks?

**Comment by braver** [comment]
@hsghori had a short play with it, it's really nifty. Had to make some changes though, because SL thinks the linter is reporting some error if we listen to both stdout and stderr. This works for me:

```
from SublimeLinter.lint import Linter, STREAM_STDOUT


class CSpell(Linter):
    cmd = 'cspell ${file}'
    defaults = {'selector': 'source'}
    error_stream = STREAM_STDOUT
    regex = r'^(?P<filename>[^:]*):(?P<line>\d+):(?P<col>\d+) - (?P<message>.*)$'
```

**Comment by hsghori** [comment]
Thanks for the comments! I've updated the linter.

**Comment by braver** [comment]
Thanks!

**Pull request merged**
