### PR TITLE
Add Linter support for JedWatson's Happiness

### PR DESCRIPTION
**Pull request by nmn**

### CODE REVIEW

**Comment by grotewold** [comment]
https://github.com/nmn/SublimeLinter-contrib-happiness/blob/master/messages.json#L3 This is pointing at a nonexistent file.

**Comment by nmn** [comment]
@grotewold Thanks, missed a typo there. Will fix it now.

**Comment by nmn** [comment]
Fixed.

**Comment by grotewold** [comment]
Thank you!

**Pull request merged**
