### PR TITLE
Add SublimeLinter-salt-lint to contrib.json

### PR DESCRIPTION
**Pull request by arjenzijlstra**

### CODE REVIEW

**Comment by braver** [comment]
Looks simple enough. You need to create a release (e.g. 1.0.0) though. @kaste have anything say?

**Comment by arjenzijlstra** [comment]
Just now created release v1: https://github.com/warpnet/SublimeLinter-salt-lint/releases/tag/v1

**Comment by braver** [comment]
Yeah, it needs to be a valid semver formatted release / tag

**Comment by kaste** [comment]
Otherwise lgtm.

**Comment by arjenzijlstra** [comment]
Edited the tag!

**Comment by braver** [comment]
🎉

**Comment by kaste** [comment]
🏎

**Pull request merged**
