### PR TITLE
Add SublimeLinter-contrib-black

### PR DESCRIPTION
**Pull request by pinle-go**

### CODE REVIEW

**Comment by kaste** [comment]
Hi! Can you tell us how this should work? What's the expected user experience here since black is a code formatter.

**Comment by pinle-go** [comment]
Sorry I forget to mention this.

In short, the "linter" formats the code file. Every time this linter is triggered, it tries to format current code file and shows errors if the code-format is not successfully.

I'm not sure if code formatting can be integrated into the SublimeLinter framework. I like both SublimeLinter and black, so I wrote this and tried to see if I can share it with others. Let me know if there are any questions! Thank you

**Comment by kaste** [comment]
🤔 	By default, this linter will run in the background while editing. Isn't it? Shouldn't it run on save or per request (manually) only?

If black can't format the file, it basically means the file has syntax errors. I don't see that you mark the syntax error in the view/buffer. Will you just show the plain error message (like what we have on the command line) in the SublimeLinter error panel?

(Btw. have you seen sublack https://github.com/jgirardet/sublack ?)

Just as a user, a nice application for a linter or sublack would be if you would basically run `black diff` against the buffer, and then add gutter marks to the lines that will get reformatted by black. So to speak, black as a linter would detect and mark all styling 'errors/violations'.

**Comment by pinle-go** [comment]
>  By default, this linter will run in the background while editing. Isn't it? Shouldn't it run on save or per request (manually) only?

Yes. Yes.

> If black can't format the file, it basically means the file has syntax errors. I don't see that you mark the syntax error in the view/buffer. Will you just show the plain error message (like what we have on the command line) in the SublimeLinter error panel?

Currently, it just silently tries to format and will do nothing if there is syntax error. I didn't think of this before but now I realized your suggestions look great.

> (Btw. have you seen sublack https://github.com/jgirardet/sublack ?)

For sublack, I was aware of it. I wanted to embed black with SublimeLinter instead of installing another plugin separately. I don't know if others have the same preferences 😐

> Just as a user, a nice application for a linter or sublack would be if you would basically run black diff against the buffer, and then add gutter marks to the lines that will get reformatted by black. So to speak, black as a linter would detect and mark all styling 'errors/violations'.

I like this, and I will see if I can get this work.

**Pull request closed without merging**
