### PR TITLE
add selene to contrib.json

### PR DESCRIPTION
**Pull request by alihsaas**

### CODE REVIEW

**Comment by braver** [comment]
Thanks!

- please place the entry in contrib.json in alphabetical order
- preferably, `cmd` is a tuple, although a string also works
- maybe add '${args}' in cmd if it needs to go before the filename

@kaste might have some more, but this looks simple enough otherwise

**Comment by kaste** [comment]
It looks like the linter does not read from stdin.  In that case you also have to set `tempfile_suffix = "-"`.

**Comment by alihsaas** [comment]
Thanks! Applied the changes you requested!

**Comment by braver** [comment]
🎉

**Pull request merged**
