### PR TITLE
Add SublimeLinter-contrib-erblint

### PR DESCRIPTION
**Pull request by TomasBarry**

### CODE REVIEW

**Comment by braver** [comment]
Thanks! 

You may want to add `${file}` and/or `${args}` to the cmd, depending on how the command should be structured.

@kaste want to have a look and give your blessings as well?

**Comment by kaste** [comment]
@TomasBarry Isn't https://github.com/Shopify/erb-lint the linter you're using here? Other than that @braver is (almost) right `cmd = 'erblint ${args} ${file_on_disk}'` signifies that you're running on real files here, not on stdin. Having `${args}` here explicitly tells SublimeLinter where it should put user provided args if any. It's just safer. 👍

**Comment by kaste** [comment]
One more thing. You do

```
    error_stream = util.STREAM_STDOUT
```

This is okay if the linter puts noise on STDERR. But if the linter just puts hard failures, config errors etc., on stderr I would leave it out because the end user will otherwise never see them.

**Comment by braver** [comment]
@TomasBarry please respond to the remarks here if you can.

**Comment by TomasBarry** [comment]
Hi @braver, I'll take a look at this again. Comments make sense.

**Comment by TomasBarry** [comment]
Hi @braver, I have addressed your comments as well as those of @kaste.

I must keep `error_stream = util.STREAM_STDOUT` as is due to the fact that noise is put out on STDERR and as a result this is how I can get actual results in the status bar for the linter.

**Comment by kaste** [comment]
LGTM

**Comment by braver** [comment]
Thanks!

**Pull request merged**
