### PR TITLE
Add SublimeLinter-addon-toggler

### PR DESCRIPTION
**Pull request by kaste**
If this is the right approach, it didn't take an hour. 😁 

I don't want this in the org bc I don't want to maintain it in the same way we maintain org stuff. Also, it becomes so official but it was meant as working documentation of how you can actually write addon plugins for SL.

### CODE REVIEW

**Comment by braver** [comment]
Ok, not having it in the org is also good. You're very close to the right approach here. Two things:

1. I'd suggest naming it "SublimeLinter Toggle". The dashes serve no purpose and changing the name format sets it apart from the sea of linter plugins. 
2. Please maintain alphabetical order in the contrib.json. I guess if you rename it as in my previous point it's already in the right place.

**Comment by kaste** [comment]
LOL

```
In [53]: "SublimeLinter-addon-toggler" < "SublimeLinter-contrib-alex"
Out[53]: True
```

I though we get a sea of addons. 😆  When I search I can probably type "SLa" and Sublime will show all addons.

**Comment by braver** [comment]
Oh jeez, good thing I'm already 🍺 My week is done.

**Comment by braver** [comment]
Yes, the name property (if set, otherwise package control takes the repository name) is the internal representation and folder name for the package.

**Comment by kaste** [comment]
Probably spaces aren't allowed then?

**Comment by braver** [comment]
They are, package control and ST itself can deal with spaces just fine. I believe it's recommended to not have spaces though. More info: https://packagecontrol.io/docs/submitting_a_package#Step_2

**Pull request merged**
